# The name of the workflow.
name: Build Test and Deploy

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

# Set environment variables
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the client application
      - name: Install and Test FrontEnd
        working-directory: ./FrontEnd
        run: |
          npm install
          npm run test

      # Install dependencies, export environment variables to be used by application and run tests for the server application
      - name: Install and Test BackEnd
        working-directory: ./BackEnd
        run: |
          npm install
          export MONGODB_URI=$MONGODB_URI
          npm run test

      # Build a Docker image for the client application
      - name: Build FE Docker Image
        working-directory: ./FrontEnd
        # Build image with tag davestain/todo-app:frontend
        run: |
          docker build -t davestain/todo-app:frontend-${{github.run_number}} .

      # Build a Docker image for the server application
      - name: Build BE Docker Image
        working-directory:
          ./BackEnd
          # Build image with tag davestain/todo-app:backend
        run: |
          docker build -t davestain/todo-app:backend-${{github.run_number}} .

      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push davestain/todo-app:frontend-${{github.run_number}}
          docker push davestain/todo-app:backend-${{github.run_number}}
